version: '3.8'

services:
  db:
    image: postgres:16-alpine
    environment:
      - POSTGRES_DB=files_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  s3:
    image: localstack/localstack:3.0
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3
      - DEFAULT_REGION=us-east-1

  front:
    build:
      context: ./front
    ports:
      - "3001:3001"

  api:
    build:
      context: ./api
    ports:
      - "3000:3000"
    environment:
      - S3_ENDPOINT=http://s3:4566
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=files_db
      - DB_USER=postgres
      - DB_PASSWORD=postgres
    depends_on:
      - db
      - s3

volumes:
  postgres_data:

networks:
  default:
    name: clojure_network
